# spring
spring:
  profiles: prod
  application:
    name: armer-user
  # 数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/armer?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: mysql
      initial-size: 3
      max-active: 20
      min-idle: 3
      max-wait: 60000
  # thymeleaf 页面渲染
  thymeleaf:
    cache: false  #将页面的缓存关闭，不然我们改变页面之后可能不能及时看到更改的内容，默认是true
    prefix: classpath:/templates/
    suffix: .html
    mode: html
    encoding: utf-8
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.armer.model
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
    call-setters-on-nulls: false
    jdbc-type-for-null: null
